on: 
  push:
    branches: [main, development]
jobs:
  test:
    strategy:
      matrix:
        os: [macos-13, [self-hosted, vs-franqueado], windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip
      - name: Install Python setup tools
        run: pip install setuptools
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'npm'
      - run: npm install-ci-test