on: 
  push:
    branches: [main, development]
jobs:
  test:
    strategy:
      matrix:
        os: [macos, ubuntu, windows]
        node-version: [16]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip
      - name: Install Python setup tools
        run: pip install setuptools
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install-ci-test